name: Docker Compose CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: ğŸ›³ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ” Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: uzimp
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: ğŸ› ï¸ Build and tag Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: ğŸ“¦ Tag & Push Backend image
        run: |
          docker tag todo101-todo-backend uzimp/todo-backend:latest
          docker push uzimp/todo-backend:latest

      - name: ğŸ–¼ï¸ Tag & Push Frontend image
        run: |
          docker tag todo101-todo-frontend uzimp/todo-frontend:latest
          docker push uzimp/todo-frontend:latest
